2. Crear vector de cero de tamaño 10

In [100]:
import numpy as np
from scipy import ndimage
from scipy import misc
import pandas as pd


In [2]:
np.zeros([10])

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Crea vector de zeros de tamaño 10 y la posicion 5 sea 1

In [5]:
array_5 = np.zeros([10])
array_5[5] = 1
array_5

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

4. Cambiar el orden de un vector de 50 elementos, el de la posicion 1 es el de la 50 etc.

In [21]:
array_de_50 = np.arange(51)
num = 50
for num in array_de_50:
    print (array_de_50[num])
    num-1
    

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50


5. Crear una matriz de 3 x 3 con valores del cero al 8

In [30]:
matriz = np.arange(9)
matriz.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

6. Encontrar los indices que no sean cero en un arreglo

In [35]:
arreglo = [1,2,0,0,4,0]
for num in arreglo:
    if (num != 0):
        print (arreglo.index(num))
    else:
        pass

0
1
4


7. Crear una matriz de identidad 3 x 3

In [36]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

8. Crear una matriz 3 x 3 x 3 con valores randomicos

In [70]:
arreglo_random = np.random.randint(0, 100, (3,3,3))
arreglo_random

array([[[56, 56, 28],
        [15, 44, 78],
        [83, 14, 66]],

       [[30, 29,  9],
        [27, 57,  6],
        [54, 17, 66]],

       [[27, 80, 28],
        [73, 23, 61],
        [31, 93, 31]]])

9. Crear una matriz 10 x 10 y encontrar el mayor y el menor

In [95]:
matriz_de_10 = np.random.randint(1, 100, (10,10))
print ('El número mayor es: ',matriz_de_10.max())
print ('El numero menor es:', matriz_de_10.min())

El número mayor es:  98
El numero menor es: 2


10. Sacar los colores RGB unicos en una imagen (cuales rgb existen ej: 0, 0, 0 - 255,255,255 -> 2 colores)

In [97]:
mapache = misc.face()
mapache

array([[[121, 112, 131],
        [138, 129, 148],
        [153, 144, 165],
        ...,
        [119, 126,  74],
        [131, 136,  82],
        [139, 144,  90]],

       [[ 89,  82, 100],
        [110, 103, 121],
        [130, 122, 143],
        ...,
        [118, 125,  71],
        [134, 141,  87],
        [146, 153,  99]],

       [[ 73,  66,  84],
        [ 94,  87, 105],
        [115, 108, 126],
        ...,
        [117, 126,  71],
        [133, 142,  87],
        [144, 153,  98]],

       ...,

       [[ 87, 106,  76],
        [ 94, 110,  81],
        [107, 124,  92],
        ...,
        [120, 158,  97],
        [119, 157,  96],
        [119, 158,  95]],

       [[ 85, 101,  72],
        [ 95, 111,  82],
        [112, 127,  96],
        ...,
        [121, 157,  96],
        [120, 156,  94],
        [120, 156,  94]],

       [[ 85, 101,  74],
        [ 97, 113,  84],
        [111, 126,  97],
        ...,
        [120, 156,  95],
        [119, 155,  93],
        [118, 154,  92]]

11. ¿Como crear una serie de una lista, diccionario o arreglo

In [104]:
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))

serie_mylist = pd.Series(mylist)
serie_myarr = pd.Series(myarr)
serie_mydict = pd.Series(mydict)

print(serie_mylist)
print(serie_myarr)
print(serie_mydict)


0     a
1     b
2     c
3     e
4     d
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
dtype: object
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
12    12
13    13
14    14
15    15
16    16
17    17
18    18
19    19
20    20
21    21
22    22
23    23
24    24
25    25
dtype: int32
a     0
b     1
c     2
e     3
d     4
f     5
g     6
h     7
i     8
j     9
k    10
l    11
m    12
n    13
o    14
p    15
q    16
r    17
s    18
t    19
u    20
v    21
w    22
x    23
y    24
z    25
dtype: int64


12. ¿Como convertir el indice de una serie en una columna de un DataFrame?

In [106]:
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict) 
df1 = pd.DataFrame(ser)
print(df1)

    0
a   0
b   1
c   2
e   3
d   4
f   5
g   6
h   7
i   8
j   9
k  10
l  11
m  12
n  13
o  14
p  15
q  16
r  17
s  18
t  19
u  20
v  21
w  22
x  23
y  24
z  25


13. ¿Como combinar varias series para hacer un DataFrame?

In [109]:
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))

nuevo_df = def1 = pd.DataFrame(ser1)
nuevo_df[1] = ser2

print (nuevo_df)

    0   1
0   a   0
1   b   1
2   c   2
3   e   3
4   d   4
5   f   5
6   g   6
7   h   7
8   i   8
9   j   9
10  k  10
11  l  11
12  m  12
13  n  13
14  o  14
15  p  15
16  q  16
17  r  17
18  s  18
19  t  19
20  u  20
21  v  21
22  w  22
23  x  23
24  y  24
25  z  25


14. ¿Como obtener los items que esten en una serie A y no en una serie B?

15. ¿Como obtener los items que no son comunes en una serie A y serie B?

16. ¿Como obtener el numero de veces que se repite un valor en una serie?

In [ ]:
veces_repetidas = def6.groupby('Index').count()['Letras']