In [2]:
#pip install numpy
import numpy as np

In [4]:
print(type([1,2,3]))
print(type((1,2,3)))
print(type(np.array([1,2,3])))
print(type(np.array((1,2,3))))

<class 'list'>
<class 'tuple'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [3]:
#Llenar matriz con 0
#Con n dimensiones
np.zeros([1])
np.zeros([3, 7, 8])

array([[[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]]])

In [10]:
np.zeros((5,7,8))

array([[[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.,

In [11]:
#Llenar matriz con 1
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
#Matriz con 1 diagonal
#4x4
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
#Crear una lista con n elementos
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [18]:
#Lista de números del 4 al 20
#Intervalo abierto
np.arange(4,20)  #[4,20[

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [20]:
np.arange(-1)

array([], dtype=int32)

In [21]:
#Lista de números negativos
np.arange(-12, 1)

array([-12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0])

In [22]:
#Lista del 0 al 20 de 2 en 2
arreglo_pares = np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [4]:
#Lista del 0 al 20 saltos en decimales
#Tanto positivos como negativos
np.arange(-12, 1, 0.5)

array([-12. , -11.5, -11. , -10.5, -10. ,  -9.5,  -9. ,  -8.5,  -8. ,
        -7.5,  -7. ,  -6.5,  -6. ,  -5.5,  -5. ,  -4.5,  -4. ,  -3.5,
        -3. ,  -2.5,  -2. ,  -1.5,  -1. ,  -0.5,   0. ,   0.5])

In [47]:
#Ver tamaño del arreglo
arreglo_pares = np.arange(0, 20, 2)
print(arreglo_pares.size)
print(len(arreglo_pares))
arreglo_tres_dimensiones = np.zeros((2,3,4))
print(arreglo_tres_dimensiones.shape)

10
10
(2, 3, 4)


In [34]:
#Cambiar de dimensiones al arreglo de 10 elementos
arreglo_pares.reshape(5,2)
arreglo_pares.reshape(2,5)

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [48]:
arreglo_varias_dimensiones = np.arange(24)
print(arreglo_varias_dimensiones)
print(arreglo_varias_dimensiones.reshape(24))
print(arreglo_varias_dimensiones.reshape(12,2))
print(arreglo_varias_dimensiones.reshape(2,12))
print(arreglo_varias_dimensiones.reshape(3,8))
print(arreglo_varias_dimensiones.reshape(8,3))
print(arreglo_varias_dimensiones.reshape(4,6))
print(arreglo_varias_dimensiones.reshape(6,4))
print(arreglo_varias_dimensiones.reshape(2,2,6))
print(arreglo_varias_dimensiones.reshape(2,4,3))
print(arreglo_varias_dimensiones.reshape(2,6,2))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]]

 [[12 13 14 15 16 17]
  [18 19 20 21 22 23]]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]
  [18 19]
  [20 2

In [ ]:
#Al arange se puede ahcer un reshape
np.arange(10).reshape(2,5)

In [50]:
a = np.array([10,10,10])
b = np.array([5,5,5])
#Sumar arreglos 
a+b

array([15, 15, 15])

In [51]:
#Resta de arreglos
a-b

array([5, 5, 5])

In [52]:
#Multiplicacion
a*b

array([50, 50, 50])

In [ ]:
#Division
a/b

In [86]:
c = np.arange(1,100,0.5)
d = np.arange(1,199,1)
c+d





array([  2. ,   3.5,   5. ,   6.5,   8. ,   9.5,  11. ,  12.5,  14. ,
        15.5,  17. ,  18.5,  20. ,  21.5,  23. ,  24.5,  26. ,  27.5,
        29. ,  30.5,  32. ,  33.5,  35. ,  36.5,  38. ,  39.5,  41. ,
        42.5,  44. ,  45.5,  47. ,  48.5,  50. ,  51.5,  53. ,  54.5,
        56. ,  57.5,  59. ,  60.5,  62. ,  63.5,  65. ,  66.5,  68. ,
        69.5,  71. ,  72.5,  74. ,  75.5,  77. ,  78.5,  80. ,  81.5,
        83. ,  84.5,  86. ,  87.5,  89. ,  90.5,  92. ,  93.5,  95. ,
        96.5,  98. ,  99.5, 101. , 102.5, 104. , 105.5, 107. , 108.5,
       110. , 111.5, 113. , 114.5, 116. , 117.5, 119. , 120.5, 122. ,
       123.5, 125. , 126.5, 128. , 129.5, 131. , 132.5, 134. , 135.5,
       137. , 138.5, 140. , 141.5, 143. , 144.5, 146. , 147.5, 149. ,
       150.5, 152. , 153.5, 155. , 156.5, 158. , 159.5, 161. , 162.5,
       164. , 165.5, 167. , 168.5, 170. , 171.5, 173. , 174.5, 176. ,
       177.5, 179. , 180.5, 182. , 183.5, 185. , 186.5, 188. , 189.5,
       191. , 192.5,

In [76]:
#Modulo Mod
a%b

array([0, 0, 0], dtype=int32)

In [95]:
#Multiplicacio con un escalar
a*10
#Suma con un escalar
a+10
#Resta con un escalar
a-10
#Division con un escalar
a/12
#Mod
a%4

array([2, 2, 2], dtype=int32)

In [104]:
#Numeros mayores a # de una arreglo
arreglo_muestra = np.arange(20).reshape(5,2,2) 
respuesta = arreglo_muestra > 5
respuesta  # Genera una matriz de booleanos
arreglo_muestra[respuesta]  # Imprimir los numeros mayores a 5 d la matriz

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [157]:
#Rango de números en un arreglo
respuesta =  arreglo_muestra > 6, arreglo_muestra, 14
#arreglo_muestra[respuesta]
respuesta
#print(arreglo_muestra)
#print(respuesta)

(array([[[False, False],
         [False, False]],
 
        [[False, False],
         [False,  True]],
 
        [[ True,  True],
         [ True,  True]],
 
        [[ True,  True],
         [ True,  True]],
 
        [[ True,  True],
         [ True,  True]]]), array([[[ 0,  1],
         [ 2,  3]],
 
        [[ 4,  5],
         [ 6,  7]],
 
        [[ 8,  9],
         [10, 11]],
 
        [[12, 13],
         [14, 15]],
 
        [[16, 17],
         [18, 19]]]), 14)

In [169]:
#Rango de números en un arreglo
respuesta =  arreglo_muestra > 6 & arreglo_muestra < 14 & arreglo_muestra%2
respuesta


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [170]:
arreglo_muestra[(arreglo_muestra>5) * (arreglo_muestra<12) * (arreglo_muestra%2==0)]
arreglo_muestra

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]]])

In [171]:
A = np.arange(4).reshape((2,2))
A

array([[0, 1],
       [2, 3]])

In [174]:
B = np.arange(4,8).reshape((2,2))
B

array([[4, 5],
       [6, 7]])

In [175]:
#Producto punto
A.dot(B)

array([[ 6,  7],
       [26, 31]])

In [176]:
B.dot(A)

array([[10, 19],
       [14, 27]])

In [177]:
arreglo_doce = np.arange(12)
arreglo_doce

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [178]:
#Suma de todo el arreglo
arreglo_doce.sum()

66

In [179]:
#Valor minimo del arreglo
arreglo_doce.min()

0

In [181]:
#Valor maximo del arreglo
arreglo_doce.max()

11

In [186]:
#Suma por posiciones 
arreglo_doce.reshape(3,2,2).sum(axis=0)


array([[12, 15],
       [18, 21]])

In [184]:
#
arreglo_doce.reshape(3,2,2).sum(axis=1)

array([[ 2,  4],
       [10, 12],
       [18, 20]])

In [185]:
#
arreglo_doce.reshape(3,2,2).sum(axis=2)

array([[ 1,  5],
       [ 9, 13],
       [17, 21]])

axis = 0 -> suma por posiciones
axis = 1 -> forma una matriz sumando los valores verticalmente de cada matriz (eje x)
axis = 2 -> forma una matriz sumando los valores horizontalmente de cada matriz (eje y)